-- Experiment 3

CREATE TABLE CLIENT_MASTER(CLIENTNO Varchar(6) Check (CLIENTNO LIKE 'C%') PRIMARY KEY,
NAME Varchar(20) NOT NULL,
ADDRESS1 Varchar(30),
ADDRESS2 Varchar(30),
CITY Varchar(15),
PINCODE INT,
STATE Varchar(15),
BALDUE dec(10,2));

CREATE TABLE PRODUCT_MASTER(PRODUCTNO Varchar(6) Check (PRODUCTNO LIKE 'P%') PRIMARY KEY,
DESCRIPTION Varchar(15) NOT NULL,
PROFITPERCENT Dec(4,2) NOT NULL,
UNIT_MEASURE Varchar(10) NOT NULL,
QTYONHAND Int NOT NULL,
REORDER_LVL Int NOT NULL,
SELLPRICE Dec(8,2) NOT NULL,
COSTPRICE Dec(8,2) NOT NULL);

CREATE TABLE SALESMAN_MASTER(SALESMANNO Varchar(6) Check (SALESMANNO LIKE 'S%') PRIMARY KEY,
SALESMANNAME Varchar(20) NOT NULL,
ADDRESS1 Varchar(30) NOT NULL,
ADDRESS2 Varchar(30),
CITY Varchar (20),
PINCODE Integer,
STATE Varchar(20),
SALAMT Real CHECK(SALAMT != 0) NOT NULL,
TGTTOGET Decimal CHECK(TGTTOGET != 0) NOT NULL,
YTDSALES Double(6,2) NOT NULL,
REMARKS Varchar(60));
