-- 1.
CREATE TABLE AUTHOR(
AUTHOR_ID CHAR(5) NOT NULL PRIMARY KEY,
LASTNAME CHAR(15) NOT NULL,
FIRSTNAME CHAR(15) NOT NULL,
EMAIL CHAR(40),
CITY CHAR(15),
COUNTRY CHAR(15)
);

-- 2.
CREATE TABLE BOOK(
BOOK_ID CHAR(5) NOT NULL PRIMARY KEY CHECK(BOOK_ID LIKE 'B%'),
BOOK_TITLE CHAR(40) NOT NULL,
COPIES INT CHECK(COPIES>2)
);

-- 3.
CREATE TABLE AUTHOR_LIST(
AUTHOR_ID CHAR(15),
BOOK_ID CHAR(5),
ROLE CHAR(5),
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID),
PRIMARY KEY(AUTHOR_ID,BOOK_ID)
);

-- 4.
INSERT INTO AUTHOR VALUES
('AAAAA','BOND','RUSKIN','RUSKIN@BOND.COM','KASAULI','INDIA'),
('BBBBB','MURTY','SUDHA','SUDHA@INFOSYS.COM','BANGALORE','INDIA'),
('CCCCC','ROWLING','JK','JKROWINLING@POTTERMORE.COM','YATE','ENGLAND'),
('DDDDD','FLEMING','IAN','IANFLEMING@OUTLOOK.COM','LONDON','UK');

INSERT INTO BOOK VALUES
('BAAAA','THE PHILOSOPHERS STONE','3'),
('BBBBB','GRANDMA BAG OF STORIES','5'),
('BCCCC','CHERRY TREE','7'),
('BDDDD','CASINO ROYALE','4');

INSERT INTO AUTHOR_LIST VALUES
('AAAAA','BAAAA','BESTS'),
('BBBBB','BBBBB','FAVRT'),
('CCCCC','BCCCC','HIGHV'),
('DDDDD','BDDDD','CLASC');

-- 5.
ALTER TABLE AUTHOR_LIST ADD COLUMN PUBLISHER CHAR(30);